version: '3'

services:

  app:
    build: ./server
    image: app_chat
    volumes:
      - ./server:/data/app
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    links:
      - redis
    networks:
      - webnet

  frontend:
    build: ./frontend
    image: frontend_chat
    volumes:
      - ./frontend/src:/data/app/src
    ports:
      - 3000:3000
      - 35729:35729

  nginx:
    build: ./dockers/nginx
    image: nginx_chat
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - webnet

  redis:
    image: redis:3.2.11-alpine
    ports:
      - 6379:6379
    networks:
      - webnet

#  wowza:
#    build: ./dockers/wowza
#    image: wowza_chat
#    environment:
#      - WSE_MGR_USER=admin
#      - WSE_MGR_PASS=admin
#      - WSE_LIC=
#    ports:
#      - 1935:1935
#      - 8086:8086
#      - 8087:8087
#      - 8088:8088

networks:
  webnet:
